# Generated by Django 4.1.1 on 2022-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=50)),
                ('user', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('category_id', models.IntegerField()),
                ('user', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
