# Generated by Django 4.1.1 on 2022-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
